---
- name: Converge
  hosts: all
  roles:
    - ansible-role-linux-bind
  vars:
    bind_acls:
      - name: acl_1
        match_list:
          - 10.0.0.0/24
          - 10.0.1.0/24
          - 10.0.2.0/24
      - name: acl_2
        match_list:
          - 10.1.0.0/16
          - 10.2.0.0/16
      - name: acl_3
        match_list:
          - 10.3.0.0/16
          - 10.4.0.0/16
      - name: docker
        match_list:
          - 172.17.0.0/24
    bind_allow_query:
      - localhost
      - docker
    bind_listen_ipv4:
      - port: 53
        match_list: ['any']
      - port: 5353
        match_list: ['any']
    bind_recursion: true
    bind_tsig_keys:
      - name: tsig_example
        algorithm: hmac-md5
        secret: 'mZiMNOUYQPMNwsDzrX2ENw=='
    bind_zones:
      - name: example.com
        type: slave
        masters:
          - 127.0.0.1
          - 127.0.0.2 key "tsig_example"
        allow_notify: ['127.0.0.3', '127.0.0.4']
        also_notify: ['127.0.0.4', '127.0.0.5']
        allow_transfer: ['127.0.0.4', '127.0.0.5']
        notify_source_v4: 127.0.0.11
    bind_notify_source_v4: 127.0.0.10
